"""Added About Author

Revision ID: 3074a9da8669
Revises: 82b532be07f4
Create Date: 2024-05-25 14:27:45.424501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3074a9da8669'
down_revision = '82b532be07f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
