"""added filefield

Revision ID: 392b7d004a60
Revises: 3074a9da8669
Create Date: 2024-05-25 18:16:23.443837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392b7d004a60'
down_revision = '3074a9da8669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
